//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel.Registration.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LnkRoleAction
    {
        public int RoleActionId { get; set; }
        public int ActionId { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<int> CurrentDispositionId { get; set; }
        public int PageId { get; set; }
        public Nullable<int> ActionGroup { get; set; }
    }
}
