//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel.Registration.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LnkUserInfoRole
    {
        public int UserInfoRoleId { get; set; }
        public int UserInfoId { get; set; }
        public int UserRoleId { get; set; }
        public bool IsActive { get; set; }
    }
}
