//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel.Registration.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LnkUserComponent
    {
        public int LnkComponentId { get; set; }
        public int ComponentId { get; set; }
        public bool IsParalegal { get; set; }
        public bool IsAttorney { get; set; }
        public bool IsIntlParalegal { get; set; }
        public bool IsIntlAttorney { get; set; }
        public bool IsPatentLead { get; set; }
        public int UserInfoId { get; set; }
        public bool IsActive { get; set; }
    }
}
